version: "3.9"
services:
  auth:
    restart: always
    build:
      context: ./backend/auth-service
    ports:
      - "3080:3080"
    volumes:
      - /app/node_modules
      - ./backend/auth-service:/app
  frontend:
    stdin_open: true
    build:
      context: ./frontend
    ports:
      - "80:3000"
    volumes:
      - /home/node/app/node_modules
      - ./frontend:/home/node/app
