version: "3.9"
services:
  auth:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
      auth:
        restart: always
        build: .
        ports:
          - "3000:3000"
        volumes:
          - /app/node_modules
          - .:/app
